# 同步 Harbor 服务镜像

name: Synchronize images - Harbor

on:
  workflow_dispatch: []
  push:
    branches:
      - 'main'
      - 'release'
    paths:
      - 'images/harbor.yaml'

env:
  REGISTRY: "${{ vars.PUBLIC_CR_REGISTRY }}"
  REPOSITORY: "${{ vars.PUBLIC_CR_REPOSITORY }}"
  USERNAME: "${{ secrets.PUBLIC_CR_USERNAME }}"
  PASSWORD: "${{ secrets.PUBLIC_CR_PASSWORD }}"
  IMAGEFILE: images/images.yaml
  ACTIONSFILE: .github/workflows/harbor.yaml

jobs:
  skopeo-sync-images:
    runs-on: ubuntu-latest
    timeout-minutes: 1200
    permissions:
      contents: read
      packages: write
      attestations: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to the Container registry
        run: echo "${{ env.PASSWORD }}" | skopeo login --authfile=auth.json -u "${{ env.USERNAME }}" --password-stdin ${{ env.REGISTRY }}

      - name: Synchronize Container images To ${{ env.REGISTRY }}
        # run: skopeo sync --keep-going --src yaml --dest docker ${{ env.IMAGEFILE }} ${{ env.REGISTRY }}/${{ env.REPOSITORY }}/
        run: |
          docker run --rm -v ./${{ env.IMAGEFILE }}:/${{ env.IMAGEFILE }} quay.io/skopeo/stable:latest \
            sync --dest-username="${{ env.USERNAME }}" --dest-password="${{ env.PASSWORD }}" \
            --keep-going --src yaml --dest docker /${{ env.IMAGEFILE }} ${{ env.REGISTRY }}/${{ env.REPOSITORY }}/
