# Skopeo copy 脚本同步镜像

name: Synchronize images - Copy

on:
  workflow_dispatch:
  push:
    branches: 
      - 'main'
      - 'release'
    paths:
      - 'images/images01.yaml'
      - 'images/images02.yaml'

env:
  REGISTRY: "${{ vars.HARBOR_REGISTRY }}"
  REPOSITORY: "${{ vars.HARBOR_REPOSITORY }}"
  USERNAME: "${{ secrets.HARBOR_USERNAME }}"
  PASSWORD: "${{ secrets.HARBOR_PASSWORD }}"
  ACTIONSFILE: .github/workflows/skopeo-copy.yaml

jobs:
  skopeo-copy-images:
    runs-on: ubuntu-latest
    timeout-minutes: 1200
    permissions:
      contents: write
      packages: write
      attestations: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to the Container registry
        run: echo "${{ env.PASSWORD }}" | skopeo login -u "${{ env.USERNAME }}" --password-stdin ${{ env.REGISTRY }}

      - name: Synchronize Container images To ${{ env.REGISTRY }}
        # run: skopeo copy docker://docker.io/bitnami/git:2.35.0 docker://${{ env.REGISTRY }}/${{ env.REPOSITORY }}/bitnami/git:2.35.0
        run: |
          chmod +x .github/tools/skopeo-copy.sh
          for f in $(yq '.on.push.paths[]' "${{ env.ACTIONSFILE }}"); \
            do eval test -f ${f} && eval .github/tools/skopeo-copy.sh "${f}" "${{ env.REGISTRY }}/${{ env.REPOSITORY }}"; done

      - name: Commit Synchronize Status
        uses: EndBug/add-and-commit@v9
        with:
          author_name: Github Actions
          author_email: mail@example.com
          message: 'Add by Github Actions'
          add: '*.sync --force'
          cwd: './images/'
